In [15]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split


---

## Split the Data into Training and Testing Sets

### Step 1: Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

In [2]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
lending_data_df=pd.read_csv(Path('Resources/lending_data.csv'))

# Review the DataFrame
lending_data_df.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  loan_status  
0                 1       22800            0  
1                 0       13600            0  
2                 0       16100            0  
3                 1       22700            0  
4                 1       23000            0

In [24]:
lending_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77536 entries, 0 to 77535
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   loan_size         77536 non-null  float64
 1   interest_rate     77536 non-null  float64
 2   borrower_income   77536 non-null  int64  
 3   debt_to_income    77536 non-null  float64
 4   num_of_accounts   77536 non-null  int64  
 5   derogatory_marks  77536 non-null  int64  
 6   total_debt        77536 non-null  int64  
 7   loan_status       77536 non-null  int64  
dtypes: float64(3), int64(5)
memory usage: 4.7 MB


### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

In [18]:
# Separate the data into labels and features
#????????????????????
# Why is re-scaling not important here????

# Separate the y variable, the labels
y=lending_data_df['loan_status'].values

# Separate the X variable, the features
X=lending_data_df.iloc[:,:-1].values

In [19]:
# Review the y variable Series
y[:5]

array([0, 0, 0, 0, 0])

In [20]:
# Review the X variable, as array of arrays (----DataFrame)
X[:9]

array([[1.07000000e+04, 7.67200000e+00, 5.28000000e+04, 4.31818182e-01,
        5.00000000e+00, 1.00000000e+00, 2.28000000e+04],
       [8.40000000e+03, 6.69200000e+00, 4.36000000e+04, 3.11926606e-01,
        3.00000000e+00, 0.00000000e+00, 1.36000000e+04],
       [9.00000000e+03, 6.96300000e+00, 4.61000000e+04, 3.49240781e-01,
        3.00000000e+00, 0.00000000e+00, 1.61000000e+04],
       [1.07000000e+04, 7.66400000e+00, 5.27000000e+04, 4.30740038e-01,
        5.00000000e+00, 1.00000000e+00, 2.27000000e+04],
       [1.08000000e+04, 7.69800000e+00, 5.30000000e+04, 4.33962264e-01,
        5.00000000e+00, 1.00000000e+00, 2.30000000e+04],
       [1.01000000e+04, 7.43800000e+00, 5.06000000e+04, 4.07114625e-01,
        4.00000000e+00, 1.00000000e+00, 2.06000000e+04],
       [1.03000000e+04, 7.49000000e+00, 5.11000000e+04, 4.12915851e-01,
        4.00000000e+00, 1.00000000e+00, 2.11000000e+04],
       [8.80000000e+03, 6.85700000e+00, 4.51000000e+04, 3.34811530e-01,
        3.00000000e+00, 0

### Step 3: Check the balance of the labels variable (`y`) by using the `value_counts` function.

In [17]:
# Check the balance of our target values
lending_data_df['loan_status'].value_counts()

loan_status
0    75036
1     2500
Name: count, dtype: int64

### Step 4: Split the data into training and testing datasets by using `train_test_split`.

In [16]:
# Split the data using train_test_split
# Assign a random_state of 1 to the function
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, 
                                                    stratify=y)

In [40]:
display(X_train[:4])
display(y_train[:4])

array([[8.50000000e+03, 6.72200000e+00, 4.39000000e+04, 3.16628702e-01,
        3.00000000e+00, 0.00000000e+00, 1.39000000e+04],
       [1.00000000e+04, 7.36000000e+00, 4.99000000e+04, 3.98797595e-01,
        4.00000000e+00, 0.00000000e+00, 1.99000000e+04],
       [8.40000000e+03, 6.70800000e+00, 4.37000000e+04, 3.13501144e-01,
        3.00000000e+00, 0.00000000e+00, 1.37000000e+04],
       [1.10000000e+04, 7.77900000e+00, 5.38000000e+04, 4.42379182e-01,
        5.00000000e+00, 1.00000000e+00, 2.38000000e+04]])

array([0, 0, 0, 0])

---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

In [21]:
# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
l_r_model=LogisticRegression(solver='lbfgs', random_state=1)

# Fit the model using training data
l_r_model.fit(X_train,y_train)

LogisticRegression(random_state=1)

### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [23]:
# Make a prediction using the testing data
test_predictions=l_r_model.predict(X_test)
predictions_df=pd.DataFrame({'predicted':test_predictions,'expected':y_test})
predictions_df.head()

predicted  expected
0          0         0
1          0         1
2          0         0
3          0         0
4          0         0

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [26]:
# Print the balanced_accuracy score of the model
balanced_accuracy_score(y_test,test_predictions)

0.9442676901753825

In [27]:
# Generate a confusion matrix for the model
confusion_matrix(y_test,test_predictions)

array([[18679,    80],
       [   67,   558]])

In [47]:
# Print the classification report for the model
target_names_l=['healthy loan','high-risk loan'] # 1->high-risk loan, 0->healthy loan
print(classification_report(y_test,test_predictions, target_names=target_names_l))

                precision    recall  f1-score   support

  healthy loan       1.00      1.00      1.00     18759
high-risk loan       0.87      0.89      0.88       625

      accuracy                           0.99     19384
     macro avg       0.94      0.94      0.94     19384
  weighted avg       0.99      0.99      0.99     19384



### Step 4: Answer the following question.

**Question:** How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** WRITE YOUR ANSWER HERE!

---

## Predict a Logistic Regression Model with Resampled Training Data

### Step 1: Use the `RandomOverSampler` module from the imbalanced-learn library to resample the data. Be sure to confirm that the labels have an equal number of data points. 

In [44]:
# Import the RandomOverSampler module form imbalanced-learn
from imblearn import over_sampling

# Instantiate the random oversampler model
# # Assign a random_state parameter of 1 to the model
ros = imblearn.over_sampling.RandomOverSampler(random_state=1)

# Fit the original training data to the random_oversampler model
X_train_resampl, y_train_resampl = ros.fit_resample(X_train, y_train)


ImportError: cannot import name '_check_X' from 'imblearn.utils._validation' (/Users/anna/anaconda3/lib/python3.11/site-packages/imblearn/utils/_validation.py)

In [50]:
# to delete this part
X_train_resampl, y_train_resampl = X_train, y_train
display(X_train_resampl)
display(y_train_resampl)
# to delete

array([[8.500e+03, 6.722e+00, 4.390e+04, ..., 3.000e+00, 0.000e+00,
        1.390e+04],
       [1.000e+04, 7.360e+00, 4.990e+04, ..., 4.000e+00, 0.000e+00,
        1.990e+04],
       [8.400e+03, 6.708e+00, 4.370e+04, ..., 3.000e+00, 0.000e+00,
        1.370e+04],
       ...,
       [8.900e+03, 6.897e+00, 4.550e+04, ..., 3.000e+00, 0.000e+00,
        1.550e+04],
       [1.030e+04, 7.494e+00, 5.110e+04, ..., 4.000e+00, 1.000e+00,
        2.110e+04],
       [9.100e+03, 6.980e+00, 4.630e+04, ..., 3.000e+00, 0.000e+00,
        1.630e+04]])

array([0, 0, 0, ..., 0, 0, 0])

In [54]:
# Count the distinct values of the resampled labels data
temp=len(X_train_resampl)
display(f'Size of training data: {temp}')
temp=len([i for i in y_train_resampl if i==1])
display(f'Count of high-risk loans:  {temp}')
temp=len([i for i in y_train_resampl if i==0])
display(f'Count of healthy loans:  {temp}')

'Size of training data 58152'

'Count of high-risk loans  1875'

'Count of healthy loans  56277'

### Step 2: Use the `LogisticRegression` classifier and the resampled data to fit the model and make predictions.

In [55]:
# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
l_r_model=LogisticRegression(solver='lbfgs', random_state=1)

# Fit the model using the resampled training data
l_r_model.fit(X_train_resampl,y_train_resampl)

# Make a prediction using the testing data
test_predictions=l_r_model.predict(X_test)
predictions_df=pd.DataFrame({'predicted':test_predictions,'expected':y_test})
predictions_df.head()

predicted  expected
0          0         0
1          0         1
2          0         0
3          0         0
4          0         0

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [61]:
# Print the balanced_accuracy score of the model 
print(f'Balanced accuracy score for the model: {balanced_accuracy_score(y_test,test_predictions):.2f}')
# Generate a confusion matrix for the model
print('Confusion matrix for the model:')
display(confusion_matrix(y_test,test_predictions))
# Print the classification report for the model
target_names_l=['healthy loan','high-risk loan']
print('Classification report for the model:')
print(classification_report(y_test,test_predictions, target_names=target_names_l))

Balanced accuracy score for the model: 0.94
Confusion matrix for the model:


array([[18679,    80],
       [   67,   558]])

Classification report for the model:
                precision    recall  f1-score   support

  healthy loan       1.00      1.00      1.00     18759
high-risk loan       0.87      0.89      0.88       625

      accuracy                           0.99     19384
     macro avg       0.94      0.94      0.94     19384
  weighted avg       0.99      0.99      0.99     19384



### Step 4: Answer the following question

**Question:** How well does the logistic regression model, fit with oversampled data, predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** YOUR ANSWER HERE!